// <auto-generated />
using System;
using AgriEnergyConnect_st10255631_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace agri_enegry.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513105529_Final")]
    partial class Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AgriEnergyConnect_st10255631_MVC.Models.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactDetails")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactDetails = "matt12@gmail.com, 555-0101",
                            Name = "Matthew Allison",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ContactDetails = "lukec@jam.org, 555-0202",
                            Name = "Luke Carlous",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("AgriEnergyConnect_st10255631_MVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Outdoor",
                            FarmerId = 1,
                            Name = "Solar Panel",
                            ProductionDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Poultry",
                            FarmerId = 1,
                            Name = "Free-Range Eggs",
                            ProductionDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Bakery",
                            FarmerId = 2,
                            Name = "Artisan Bread",
                            ProductionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruit",
                            FarmerId = 2,
                            Name = "Fresh Strawberries",
                            ProductionDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AgriEnergyConnect_st10255631_MVC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "cliveemp123",
                            Role = "Employee",
                            Username = "Clive"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "southafrica",
                            Role = "Farmer",
                            Username = "Matt"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "suidAfrika",
                            Role = "Farmer",
                            Username = "LukeC"
                        });
                });

            modelBuilder.Entity("AgriEnergyConnect_st10255631_MVC.Models.Farmer", b =>
                {
                    b.HasOne("AgriEnergyConnect_st10255631_MVC.Models.User", "User")
                        .WithOne("FarmerProfile")
                        .HasForeignKey("AgriEnergyConnect_st10255631_MVC.Models.Farmer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgriEnergyConnect_st10255631_MVC.Models.Product", b =>
                {
                    b.HasOne("AgriEnergyConnect_st10255631_MVC.Models.Farmer", "Farmer")
                        .WithMany("Products")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("AgriEnergyConnect_st10255631_MVC.Models.Farmer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AgriEnergyConnect_st10255631_MVC.Models.User", b =>
                {
                    b.Navigation("FarmerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
